server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  redis:
    host: localhost
    port: 6379
    password: redisPasswordXXX
    database: 0
    keytimeout: 10
    timeout: 10
  redis1:
    host: localhost
    port: 6379
    password: redisPasswordXXX
    database: 0
    keytimeout: 10
    timeout: 10
    pool:
        max-idle: 10
        min-idle: 2
  redis2:
    host: 100.100.100.100
    port: 6380
    password: redisPasswordXXX
    database: 0
    keytimeout: 10
    timeout: 10
    pool:
      max-idle: 10
      min-idle: 2

  session:
    timeout: 2000
    store-type: redis

  datasource:
    url: jdbc:mysql://mysql:3306/manli?useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2b8
    username: XXXXXXX
    password: XXXXXXX
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    rest:
      base-path: /api

manli:
  sms:
    universal: "xxxx"
  upload:
    electronic_record:
      storage_prefix: "/www/upload/electronic_record/"
      website_prefix: "http://100.100.100.100/electronic_record/"
    android_pkg:
      storage_prefix: "/www/upload/android_pkg/"
      website_prefix: "http://100.100.100.100/android_pkg/"

#logging:
#  level:
#      org.springframework: debug
